---
# This playbook is used for ansible demo.
- hosts: localhost
  roles:
    - common
    - role: andrewrothstein.miniconda
      miniconda_parent_dir: "{{ prefix }}"
      miniconda_make_sys_default: True
      tags:
        miniconda
    - supervisor
    - nginx
    - pywps
